### ISSUE TITLE
Power saving mode

### ISSUE THREAD

**Issue by jcgruenhage** [christian-draeger/watch-plus-plus#1]
It would be nice to have a power saving mode that doesn't update the display every second and reduces brightness of the display backlight. Currently, the card10 doesn't last more than a few hours on battery, and it would be really nice to wear it as a clock during the day, without having to charge it during lunch.

**Comment by christian-draeger** [comment]
Hey,
I experimented a bit with the light sensor yesterday and am not sure if the light sensor on my card10 is broken. Regarding the card10 docs the light sensor shoukd return a value between ~400 (very bright) and ~8 (very dark), but im always getting a value between 8 and 15. If I interpret this MR correctly the automatic adjustment of the displays backlight will probably be included in the next firmware update (1.11): https://git.card10.badge.events.ccc.de/card10/firmware/merge_requests/266
So I think it's worth it to wait for the merge request and have native support instead of inventing the wheel again. 
But anyway, i will reduce updating the display to approximately every second later this evening.

**Comment by christian-draeger** [comment]
hey i just released a new version with reduced amount of renderings per seconds and fixed the rendering of the 7segment display after it was broken a bit after rendering changed in firmware >= 1.8
furthermore i included an automatic adjustment of the display [brightness](https://github.com/christian-draeger/watch-plus-plus/commit/a7d532fabb1496be9d7465d82b205ea20e84b403)

all of the fixes are included in revision 6 at hatchery so you could just download the app manually from [hatchery](https://badge.team/projects/watch) or use the companion app to reinstall the latest version of watch++
